# Generated by Django 3.2.14 on 2025-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='DRAFT', max_length=50),
        ),
    ]
