# Generated by Django 4.2.21 on 2025-05-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('READ', 'Lecture'), ('WRITE', 'Écriture'), ('DELETE', 'Suppression'), ('ADMIN', 'Administration')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
            ],
        ),
    ]
