# Generated by Django 4.2.21 on 2025-05-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('document', 'user', 'permission_type')},
        ),
    ]
