# Generated by Django 3.2.14 on 2025-06-14 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('string', 'Chaîne'), ('integer', 'Entier'), ('boolean', 'Booléen'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=10)),
                ('items_per_page', models.IntegerField(default=25)),
                ('default_view', models.CharField(choices=[('list', 'Liste'), ('grid', 'Grille'), ('tiles', 'Tuiles')], default='list', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=False)),
                ('auto_save_favorites', models.BooleanField(default=True)),
                ('show_hidden_files', models.BooleanField(default=False)),
                ('default_sort_field', models.CharField(choices=[('title', 'Titre'), ('created_at', 'Date de création'), ('updated_at', 'Date de modification'), ('file_size', 'Taille')], default='created_at', max_length=20)),
                ('default_sort_order', models.CharField(choices=[('asc', 'Croissant'), ('desc', 'Décroissant')], default='desc', max_length=10)),
                ('search_history_enabled', models.BooleanField(default=True)),
                ('save_searches', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GesArcEle', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('max_file_size', models.BigIntegerField(default=52428800)),
                ('allowed_file_types', models.JSONField(default=list)),
                ('max_files_per_upload', models.IntegerField(default=10)),
                ('ocr_enabled', models.BooleanField(default=True)),
                ('ocr_language', models.CharField(default='fra', max_length=10)),
                ('ocr_auto_process', models.BooleanField(default=True)),
                ('trash_retention_days', models.IntegerField(default=30)),
                ('auto_cleanup_enabled', models.BooleanField(default=True)),
                ('enable_full_text_search', models.BooleanField(default=True)),
                ('search_results_per_page', models.IntegerField(default=25)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=480)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
    ]
