# Generated by Django 4.2.21 on 2025-05-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tagger', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttag',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_documents', to='Tagger.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('document', 'tag')},
        ),
    ]
